export const PALAWAN_MUNICIPALITIES: string[] = [
  "Aborlan",
  "Agutaya",
  "Araceli",
  "Balabac",
  "Bataraza",
  "Brooke's Point",
  "Busuanga",
  "Cagayancillo",
  "Coron",
  "Culion",
  "Cuyo",
  "Dumaran",
  "El Nido",
  "Kalayaan",
  "Linapacan",
  "Magsaysay",
  "Narra",
  "Puerto Princesa",
  "Quezon",
  "Rizal",
  "Roxas",
  "San Vicente",
  "Sofronio Española",
  "Taytay",
]

export const COMMON_TAGS: string[] = [
  'Beachfront',
  'Ocean View',
  'Deep Sea',
  'Mountain View',
  'Road Access',
  'Corner Lot',
  'Titled',
  'Ready to Build',
  'Near Town Center',
  'Rice Field View',
  'Fruit Trees',
  'Ready to Operate',
  'Near Airport',
  'Near to Beach',
  'Boat Dock',
]
